### ISSUE TITLE
User

### ISSUE THREAD

**Issue by alesilveri** [RygarNelson/SmartParking#3]
# Text
With this User Story we define a general User which shares common actions among his subclasses.
The Tasks will be inherited by the subclasses. 

# Tasks
- [ ] User Registration
- [ ] User Login
- [ ] Managing Account 

### SubTasks
- [ ] User Registration (frontend)
- [ ] User Login (frontend)
- [ ] Change email (frontend)
- [ ] Change password (frontend)

- [ ] User Registration (backend)
- [ ] User Login (backend)
- [ ] Change email (backend)
- [ ] Change password (backend)
