### ISSUE TITLE
Municipality

### ISSUE THREAD

**Issue by alesilveri** [RygarNelson/SmartParking#4]
# Text
The Municipality inherit the User's characteristics and, in addition, has the following properties: it can add parking slots, with at least one sensor; it can manage parking slots and finally it can perform analytics actions, like extrapolating data.

# Tasks
### Prerequisites 
- Inherit User's properties
### Tasks
- [ ] Add parking slots 
- [ ] Manage parking slots
- [ ] Perform analytic actions
### SubTasks
- [ ] Add sensor (frontend)
- [ ] Remove sensor (frontend)
- [ ] Add parking slot (frontend)
_Note: during the registration of a new parking slot, at least one sensor has to be provided to the System_
- [ ] Change parking slot's position (frontend)
- [ ] Add one or more sensors to the parking slot (frontend)
- [ ] Remove one or more sensors to the parking slot (frontend)
_Note: at least one sensor has to be maintained on the parking slot_
- [ ] Remove parking slot (frontend)
- [ ] Perform analytic actions (frontend)

- [ ] Add sensor (backend)
- [ ] Remove sensor (backend)
- [ ] Add parking slot (backend)
_Note: during the registration of a new parking slot, at least one sensor has to be provided to the System_
- [ ] Change parking slot's position (backend)
- [ ] Add one or more sensors to the parking slot (backend)
- [ ] Remove one or more sensors to the parking slot (backend)
_Note: at least one sensor has to be maintained on the parking slot_
- [ ] Remove parking slot (backend)
- [ ] Perform analytic actions (backend)
