### ISSUE TITLE
Driver

### ISSUE THREAD

**Issue by alesilveri** [RygarNelson/SmartParking#5]
# Text
The Driver inherit the User's characteristics and, in addition, has the following properties: it can choose a final destination and manage payments.
# Tasks 
### Prerequisites
- Inherit User's properties 
- Always GPS On
### Tasks
- [ ] Set a final destination 
- [ ] Manage payments
### SubTasks
- [ ] Set a final destination (frontend)
- [ ] Insert a new credit card / bank account / other payment methods (frontend)
- [ ] Set a default payment method (frontend)
- [ ] Remove a payment method (frontend)
_Note: you cannot remove a default payment method_
