### ISSUE TITLE
Company

### ISSUE THREAD

**Issue by alesilveri** [RygarNelson/SmartParking#6]
# Text
The Company inherit the User's characteristics and, in addition, has the following properties: set a hourly price for every parking slots.
It can also put a default price whenever a new parking slot is added to the system.
# Tasks
### Prerequisites
- Inherit User's properties
### Tasks
- [ ] Set a price for a parking slot
- [ ] Set a default price 
### SubTasks
- [ ] Set a price for a parking slot (frontend)
- [ ] Set a default price (frontend)
- [ ] Set a price for a parking slot (backend)
- [ ] Set a default price (backend)
